apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozone-api
  namespace: ozone-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ozone-api
  template:
    metadata:
      labels:
        app: ozone-api
    spec:
      containers:
      - name: api
        image: ozone-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: OZONE_OM_ADDRESS
          value: "om:9862"
        - name: OZONE_SCM_ADDRESS
          value: "scm:9861"
        - name: OZONE_S3G_ADDRESS
          value: "s3g:9878"
        resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"