apiVersion: v1
kind: ConfigMap
metadata:
  name: ozone-config
  namespace: ozone-cluster
data:
  ozone-site.xml: |
    <configuration>

      <property>
        <name>ozone.metadata.dirs</name>
        <value>/data/metadata</value>
      </property>

      <property>
        <name>hdds.datanode.dir</name>
        <value>/data/datanode</value>
      </property>

      <property>
        <name>ozone.scm.names</name>
        <value>scm</value>
      </property>

      <property>
        <name>ozone.om.address</name>
        <value>om</value>
      </property>

      <property>
        <name>ozone.replication</name>
        <value>1</value>
      </property>

      <property>
        <name>ozone.om.db.dirs</name>
        <value>/data/1/om-db</value>
        <description>The directory where OM stores its RocksDB metadata.</description>
      </property>

    </configuration>