apiVersion: apps/v1
kind: Deployment
metadata:
  name: om
  namespace: ozone-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: om
  template:
    metadata:
      labels:
        app: om
    spec:
      containers:
        - name: om
          image: apache/ozone:latest
          command: ["ozone"]
          args: ["om"]
          ports:
            - containerPort: 9862
          env:
            - name: OZONE_SCM_NAMES
              value: "scm"
            - name: OZONE_HEAP_SIZE
              value: "256m"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"