apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: om
  namespace: ozone-cluster
spec:
  serviceName: om
  replicas: 1
  selector:
    matchLabels:
      app: om
  template:
    metadata:
      labels:
        app: om
    spec:
      containers:
      - name: om
        image: apache/ozone:2.0.0
        command: ["ozone"]
        args: ["om"]
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ozone-config
          mountPath: /opt/hadoop/etc/hadoop/ozone-site.xml
          subPath: ozone-site.xml
      volumes:
      - name: ozone-config
        configMap:
          name: ozone-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi