apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scm
  namespace: ozone-cluster
spec:
  serviceName: scm
  replicas: 1
  selector:
    matchLabels:
      app: scm
  template:
    metadata:
      labels:
        app: scm
    spec:
      containers:
      - name: scm
        image: apache/ozone:latest
        command: ["ozone"]
        args: ["scm"]
        ports:
        - containerPort: 9860
        volumeMounts:
        - name: data
          mountPath: /data
        - name: metadata
          mountPath: /data/ozone/meta
      volumes:
        - name: metadata
          emptyDir: {} 
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi